version: "3.9"

services:
  frontend_dev:
    container_name: ai_photoshoot_frontend_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
    # Для удобной разработки (горячая перезагрузка)
    volumes:
      - .:/app
      - /app/node_modules
